[project]
name = "doc2graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "attrdict==2.0.1",
    "easyocr==1.6.2",
    "fasttext>=0.9.2",
    "gitdb2==3.0.1",
    "gitpython>=3.1.30",
    "itsdangerous==2.0.1",
    "matplotlib==3.5.2",
    "networkx==2.8.4",
    "numpy>=1.22",
    "opencv-python==4.6.0.66",
    "pandas>=2.3.2",
    "pillow>=9.1.1",
    "pydantic==1.8.2",
    "pytesseract==0.3.9",
    "pytest>=8.4.2",
    "python-dotenv==0.20.0",
    "pyyaml==6.0",
    "ruff>=0.13.0",
    "scikit-learn==1.0.2",
    "segmentation-models-pytorch==0.2.1",
    "setuptools==65.5.1",
    "setuptools-git-versioning==1.9.2",
    "spacy==3.3.0",
    "tensorboard==2.9.1",
    "wget==3.2",
]
