# THIS YAML SETTING IS USED AS A BASE TO PRODUCE THE 'PREPROCESSING.YAML' ONE.
# THIS IT IS MEANT TO BE USED AS A STARTING POINT AND DOCUMENTATION ONE (see all the different choises a user has).

LOADER:
  src_data:
    - FUNSD
    # - PAU
    # - CUSTOM
  reshape: 900
FEATURES:
  add_text: true
  add_eweights: true
  add_layout: true
  add_visual: true
GRAPHS:
  edge_type:
    - fully
    # - knn
  data_type:
    - img
    # - pdf
  node_granularity:
    - gt
    # - ocr
    # - yolo  
  